In [1]:
import pandas as pd

In [3]:
promo_stats = pd.read_csv('../data/processed/promo_stats.csv')
promo_stats

           Date  Total_Items  Promo_Items  Promo_Ratio
0    2022-01-01           20            3         0.15
1    2022-01-02           20            4         0.20
2    2022-01-03           20            7         0.35
3    2022-01-04           20            9         0.45
4    2022-01-05           20           14         0.70
..          ...          ...          ...          ...
755  2024-01-26           20            6         0.30
756  2024-01-27           20           11         0.55
757  2024-01-28           20            7         0.35
758  2024-01-29           20            0         0.00
759  2024-01-30           20            0         0.00

[760 rows x 4 columns]

In [5]:
promo_stats.describe()  # 查看促销商品数和促销覆盖率的统计值

       Total_Items  Promo_Items  Promo_Ratio
count        760.0   760.000000   760.000000
mean          20.0     6.578947     0.328947
std            0.0     2.812841     0.140642
min           20.0     0.000000     0.000000
25%           20.0     5.000000     0.250000
50%           20.0     7.000000     0.350000
75%           20.0     8.000000     0.400000
max           20.0    14.000000     0.700000